"""Add nullable report_frequency

Revision ID: 298204bd5318
Revises: 14cbc87af0b7
Create Date: 2025-12-10 15:35:34.363979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298204bd5318'
down_revision = '14cbc87af0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_frequency', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('report_frequency')

    # ### end Alembic commands ###
