"""Add profile picture to User

Revision ID: 936e15f2cf53
Revises: fddd5a4f1838
Create Date: 2025-12-11 12:06:17.353826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936e15f2cf53'
down_revision = 'fddd5a4f1838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
