"""Add nullable monthly_budget

Revision ID: afd2f3e78237
Revises: 298204bd5318
Create Date: 2025-12-10 16:51:35.913428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd2f3e78237'
down_revision = '298204bd5318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('monthly_budget')

    # ### end Alembic commands ###
