"""empty message

Revision ID: b05697c6d69c
Revises: 55b054559457
Create Date: 2025-12-19 00:44:34.131064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05697c6d69c'
down_revision = '55b054559457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expense_history_expense_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expense_history_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expenses_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recurring_expenses_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recurring_expenses_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expenses_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('expense_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expense_history_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('expense_history_expense_id_fkey'), 'expenses', ['expense_id'], ['id'])

    # ### end Alembic commands ###
